//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int Id { get; set; }
        public string date { get; set; }
        public string country1 { get; set; }
        public string score1 { get; set; }
        public string country2 { get; set; }
        public string score2 { get; set; }
        public string img1 { get; set; }
        public string img2 { get; set; }
    }
}
