//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01football.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shoppingEntities : DbContext
    {
        public shoppingEntities()
            : base("name=shoppingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tmember> tmembers { get; set; }
        public virtual DbSet<torder> torders { get; set; }
        public virtual DbSet<torderdetail> torderdetails { get; set; }
        public virtual DbSet<tproduct> tproducts { get; set; }
    }
}
