//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01football.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class team
    {
        public long id { get; set; }
        public string couuntry { get; set; }
        public string GP { get; set; }
        public string win { get; set; }
        public string flat { get; set; }
        public string lose { get; set; }
        public string score { get; set; }
        public string loseball { get; set; }
        public string GD { get; set; }
        public string score2 { get; set; }
        public string src { get; set; }
    }
}
