//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01football.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class torderdetail
    {
        public int fid { get; set; }
        [DisplayName("訂單編號")]
        public string forderguid { get; set; }
        [DisplayName("會員帳號")]
        public string fuserid { get; set; }
        [DisplayName("產品編號")]
        public string fpid { get; set; }
        [DisplayName("品名")]
        public string fname { get; set; }
        [DisplayName("單價")]
        public Nullable<int> fprice { get; set; }
        [DisplayName("訂購數量")]
        public Nullable<int> fqty { get; set; }
        [DisplayName("是否為訂單")]
        public string fisapproved { get; set; }
    }
}
